# Generated by Django 2.2.8 on 2022-05-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='patient',
            new_name='patient_obj',
        ),
    ]
